### PR TITLE
Updates to match Parser functionality

### PR DESCRIPTION
**Pull request by danhunsaker**
- Added BSON and MSGPack support
- Added AutoDetect support (via Accept header)
- Added ResponderException and made most types throw it (QueryStr doesn't throw any in Parser, so it also doesn't in Responder)
- Updated composer.json to use the same package versions as Parser
- Updated Travis test matrix to match Parser
- Various minor/cosmetic changes to bring Responder up to date with Parser

The idea here was to be able to use Parser and Responder together to build APIs that accept and return data in the same variety of formats.  This is useful because API clients can then communicate using whichever format(s) they are most comfortable using, in both directions, bypassing the need to include their own extra parser(s)/formatter(s) to handle extraneous formats.

### CODE REVIEW

**Comment by danhunsaker** [comment]
With the merging of nathanmac/Parser#30, this PR is now out of date.  I'll work on adding the registration feature here, as well, over the weekend (assuming my kids will give me the chance).

If this PR gets merged before then, I'll happily add the registration feature in a new branch/PR instead.

**Comment by danhunsaker** [comment]
There we go.  Up to date again.  Though this PR actually includes some fixes that Parser doesn't have yet; I'll be pushing those to a new PR there shortly.

**Comment by nathanmac** [comment]
Thanks again 👍

**Comment by danhunsaker** [comment]
Of course, any time!

**Pull request merged**
